name: Continuous Integration 

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:

jobs:
  test-neovim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Setup Neovim config
        run: |
          mkdir -p ~/.config/nvim
          cp -r . ~/.config/nvim

      - name: Install plugins with Lazy.nvim
        run: |
          nvim --headless "+Lazy! sync" +qall

      - name: Run :checkhealth
        run: |
          nvim --headless -c "checkhealth" -c "q"

      - name: Run Lua tests (if any)
        run: |
          nvim --headless -c "PlenaryBustedDirectory tests/" -c "q" || echo "No tests found"

      - name: Ensure Neovim starts without errors
        run: |
          nvim --headless -c "q" || exit 1
